"""fix models

Revision ID: 0196b6fff2f2
Revises: 29f16eec2c03
Create Date: 2026-07-30 15:42:03.280666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0196b6fff2f2'
down_revision: Union[str, Sequence[str], None] = '29f16eec2c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'activity_logs', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'categories', ['kategori'])
    op.add_column('rewards', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewards', 'created_at')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    # ### end Alembic commands ###
