"""add tables2

Revision ID: 36c64ff64667
Revises: 457b03327251
Create Date: 2026-07-10 20:26:11.652433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c64ff64667'
down_revision: Union[str, Sequence[str], None] = '457b03327251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('message_detail', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('message_detail_sender_id_fkey'), 'message_detail', type_='foreignkey')
    op.create_foreign_key(None, 'message_detail', 'users', ['user_id'], ['id'])
    op.drop_column('message_detail', 'sender_id')
    op.add_column('questions', sa.Column('correct_answer', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'correct_answer')
    op.add_column('message_detail', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message_detail', type_='foreignkey')
    op.create_foreign_key(op.f('message_detail_sender_id_fkey'), 'message_detail', 'users', ['sender_id'], ['id'])
    op.drop_column('message_detail', 'user_id')
    op.drop_column('comments', 'created_at')
    # ### end Alembic commands ###
