"""rating

Revision ID: a363c43ded78
Revises: 36c64ff64667
Create Date: 2026-07-26 19:48:50.136656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a363c43ded78'
down_revision: Union[str, Sequence[str], None] = '36c64ff64667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('rating', sa.Integer(), nullable=False))
    op.drop_column('ratings', 'Rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('Rating', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('ratings', 'rating')
    # ### end Alembic commands ###
